add new php version and nginx

diff --git a/Debian/Base/entrypoint b/Debian/Base/entrypoint
--- a/Debian/Base/entrypoint
+++ b/Debian/Base/entrypoint
@@ -9,9 +9,16 @@ then
 	do
 		if [ -f $SCRIPT -a -x $SCRIPT ]
 		then
-			$SCRIPT
+            echo "Running script: $SCRIPT";
+			$SCRIPT;
+			RESULT="$?";
+			if [ $RESULT != 0 ]; then
+                echo "Error : $RESULT when executing before script: $SCRIPT"
+                exit RESULT
+            fi
 		fi
 	done
 fi
 
+echo "Starting application"
 exec "$@"
